[[help]]
print_usage_header = "---- rainy-toolkit C++ reflection code generator usage ----"

[[help.options_desc]]
input = "Let generator reads from this given file in one time"
verbose = "Show the parse process when generating file"
out = "Let generator output the generated content to another file"
help = "Show the help"
suffix = "Use suffix in the generated file name"
config = "Set the config file to overwrite global settings"
lang = "Set the display language when language packs are available."

[[easter_eggs.code_rain]]
init_text = "🌧️  Initiating Smooth Code Rain 🌧️"
press_ctrl = "Press Ctrl+C to stop early"
complete = "Code Rain Complete"
welcome_back = "Welcome back to reality"
interrupted_text = "Rain is not complete, but anyway, welcome back to reality"

[[description]]
content = '''
rainy-toolkit reflection moc compiler (prism-moc)

created-by: {authors}

prism-moc is c++ code analysis and code generation tool that use rust program language develop.
it can be used by accepted the licences APACHE 2.0.

check_hash: {git_hash}
branch: {git_branch}
build_time: {build_time}
'''
