set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR AMD64)

set(CMAKE_C_COMPILER clang-cl)
set(CMAKE_CXX_COMPILER clang-cl)

set(RAINY_USE_CROSSCOMPILE OFF)

include("${CMAKE_CURRENT_LIST_DIR}/toolchain_common.cmake")
