set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(CMAKE_C_COMPILER clang)
set(CMAKE_CXX_COMPILER clang++)

set(RAINY_USE_CROSSCOMPILE OFF)

include("${CMAKE_CURRENT_LIST_DIR}/toolchain_common.cmake")
