#include <rainy/foundation/network/config.hpp>

namespace rainy::foundation::network::implements {
    collections::dense_map<text::hashed_string, std::string_view> &content_type_map() {
        static collections::dense_map<text::hashed_string, std::string_view> instance = {{".css", "text/css"},
                                                                                         {".csv", "text/csv"},
                                                                                         {".htm", "text/html"},
                                                                                         {".html", "text/html"},
                                                                                         {".js", "text/javascript"},
                                                                                         {".mjs", "text/javascript"},
                                                                                         {".txt", "text/plain"},
                                                                                         {".vtt", "text/vtt"},
                                                                                         {".apng", "image/apng"},
                                                                                         {".avif", "image/avif"},
                                                                                         {".bmp", "image/bmp"},
                                                                                         {".gif", "image/gif"},
                                                                                         {".png", "image/png"},
                                                                                         {".svg", "image/svg+xml"},
                                                                                         {".webp", "image/webp"},
                                                                                         {".ico", "image/x-icon"},
                                                                                         {".tif", "image/tiff"},
                                                                                         {".tiff", "image/tiff"},
                                                                                         {".jpg", "image/jpeg"},
                                                                                         {".jpeg", "image/jpeg"},
                                                                                         {".mp4", "video/mp4"},
                                                                                         {".mpeg", "video/mpeg"},
                                                                                         {".webm", "video/webm"},
                                                                                         {".mp3", "audio/mp3"},
                                                                                         {".mpga", "audio/mpeg"},
                                                                                         {".weba", "audio/webm"},
                                                                                         {".wav", "audio/wave"},
                                                                                         {".otf", "font/otf"},
                                                                                         {".ttf", "font/ttf"},
                                                                                         {".woff", "font/woff"},
                                                                                         {".woff2", "font/woff2"},
                                                                                         {".7z", "application/x-7z-compressed"},
                                                                                         {".atom", "application/atom+xml"},
                                                                                         {".pdf", "application/pdf"},
                                                                                         {".json", "application/json"},
                                                                                         {".rss", "application/rss+xml"},
                                                                                         {".tar", "application/x-tar"},
                                                                                         {"xht", "application/xhtml+xml"},
                                                                                         {"xhtml", "application/xhtml+xml"},
                                                                                         {"xslt", "application/xslt+xml"},
                                                                                         {"xml", "application/xml"},
                                                                                         {"gz", "application/gzip"},
                                                                                         {"zip", "application/zip"},
                                                                                         {"wasm", "application/wasm"}};
        return instance;
    }
}
