#!/usr/bin/env python3
import argparse
import os
import platform
import re
import sys

GENERATED_DIR = os.path.normpath(
    os.path.join(os.path.dirname(__file__), "..", "generated")
)

TOOLCHAIN_TEMPLATE = """\
# Generated by generate_toolchain.py -- do not edit manually.

set(CMAKE_SYSTEM_NAME {system_name})
set(CMAKE_SYSTEM_PROCESSOR {processor})

set(CMAKE_C_COMPILER {c_compiler})
set(CMAKE_CXX_COMPILER {cxx_compiler})
{cross_setup}
set(RAINY_USE_CROSSCOMPILE {use_cross})

include("${{CMAKE_CURRENT_LIST_DIR}}/../presets/toolchain_common.cmake")
"""

CROSS_SETUP = """\
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
"""


def detect_system_name() -> str:
    sys_map = {"Linux": "Linux", "Windows": "Windows", "Darwin": "Darwin"}
    raw = platform.system()
    return sys_map.get(raw, raw)


def detect_processor() -> str:
    mach = platform.machine().lower()
    if mach in ("amd64", "x86_64", "x64"):
        return "x86_64"
    if mach in ("aarch64", "arm64"):
        return "aarch64"
    if mach.startswith("arm"):
        return "arm"
    if mach.startswith("i386") or mach.startswith("i686"):
        return "x86"
    return mach


def make_safe_filename(name: str) -> str:
    return re.sub(r"[^a-zA-Z0-9._-]", "_", name)


TARGET_ALIASES = {
    "linux-x86-64":        ("Linux", "x86_64"),
    "linux-aarch64":       ("Linux", "aarch64"),
    "linux-arm":           ("Linux", "arm"),
    "windows-x86-64":      ("Windows", "AMD64"),
    "mingw-x86-64":        ("Windows", "AMD64"),
    "darwin-x86-64":       ("Darwin", "x86_64"),
    "darwin-aarch64":      ("Darwin", "aarch64"),
}


def resolve_target(target: str) -> tuple:
    key = target.lower().replace("_", "-")
    if key in TARGET_ALIASES:
        return TARGET_ALIASES[key]
    print(f"error: unknown target '{target}'. Available: {', '.join(sorted(TARGET_ALIASES))}", file=sys.stderr)
    sys.exit(1)


def main():
    parser = argparse.ArgumentParser(
        description="Generate a CMake toolchain file for rainy-toolkit."
    )
    parser.add_argument(
        "-c", "--compiler",
        required=True,
        help="C compiler executable path or name (e.g. gcc, clang, /usr/bin/aarch64-linux-gnu-gcc)",
    )
    parser.add_argument(
        "--cxx-compiler",
        help="C++ compiler executable (default: derived from --compiler by replacing common prefixes)",
    )
    parser.add_argument(
        "-n", "--name",
        help="Toolchain name (default: derived from compiler and target)",
    )
    parser.add_argument(
        "-o", "--output",
        help="Output directory (default: toolchains/generated/)",
    )
    parser.add_argument(
        "--target",
        help="Target platform alias (e.g. linux-x86_64, linux-aarch64, windows-x86_64, darwin-aarch64). "
             "Overrides --system-name and --processor.",
    )
    parser.add_argument(
        "--system-name",
        help="Target OS (default: auto-detected from host or --target)",
    )
    parser.add_argument(
        "--processor",
        help="Target architecture (default: auto-detected from host or --target)",
    )
    parser.add_argument(
        "--cxx-standard",
        type=int,
        default=17,
        choices=[17, 20, 23, 26],
        help="C++ standard (default: 17)",
    )
    parser.add_argument(
        "--cross",
        action="store_true",
        help="Mark as cross-compilation toolchain (RAINY_USE_CROSSCOMPILE=ON)",
    )

    args = parser.parse_args()

    # Resolve target platform
    if args.target:
        sys_name, proc = resolve_target(args.target)
        if args.system_name and args.system_name != sys_name:
            print(f"warning: --target {args.target} implies --system-name {sys_name}, ignoring explicit --system-name", file=sys.stderr)
        if args.processor and args.processor != proc:
            print(f"warning: --target {args.target} implies --processor {proc}, ignoring explicit --processor", file=sys.stderr)
        args.system_name = sys_name
        args.processor = proc
    else:
        args.system_name = args.system_name or detect_system_name()
        args.processor = args.processor or detect_processor()

    # Derive C++ compiler from C compiler if not given
    if args.cxx_compiler:
        cxx_compiler = args.cxx_compiler
    else:
        replacements = [
            (r"\bgcc\b", "g++"),
            (r"\bgcc-", "g++-"),
            (r"\bclang\b", "clang++"),
            (r"\bclang-", "clang++-"),
        ]
        result = args.compiler
        for pat, repl in replacements:
            result, n = re.subn(pat, repl, result)
            if n:
                cxx_compiler = result
                break
        else:
            cxx_compiler = args.compiler + "++"

    # Determine if this is cross compilation
    if args.cross:
        cross = True
    else:
        host_name = platform.system()
        host_proc = detect_processor()
        cross = (args.system_name != host_name) or (args.processor.lower() != host_proc.lower())

    cross_setup = CROSS_SETUP.strip() if cross else ""
    use_cross = "ON" if cross else "OFF"

    # Derive name
    if args.name:
        base_name = args.name
    else:
        base = os.path.basename(args.compiler)
        base_name = f"{base}-{args.processor}-{args.system_name}"
    base_name = make_safe_filename(base_name)
    filename = f"{base_name}.cmake"

    output_dir = args.output or GENERATED_DIR
    os.makedirs(output_dir, exist_ok=True)
    output_path = os.path.join(output_dir, filename)

    content = TOOLCHAIN_TEMPLATE.format(
        system_name=args.system_name,
        processor=args.processor,
        c_compiler=args.compiler,
        cxx_compiler=cxx_compiler,
        cross_setup=cross_setup,
        use_cross=use_cross,
    )

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(content)

    print(f"Generated toolchain: {output_path}")
    print(f"  Target: {args.system_name} / {args.processor}")
    print(f"  C compiler: {args.compiler}")
    print(f"  CXX compiler: {cxx_compiler}")
    print(f"  C++ standard: C++{args.cxx_standard}")
    print(f"  Cross-compile: {cross}")


if __name__ == "__main__":
    main()
