name: MacOS-X86_64-Test

permissions:
  contents: read

on:
  push:
  pull_request:
  workflow_dispatch: # Test only

jobs:
  x86_64:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Say Hello
        run: echo "Hello World"

      - name: Display System Infomation
        run: |
          echo "Current System: $(sw_vers -productName)"
          echo "Version: $(sw_vers -productVersion)"
          echo "Hostname: $(hostname)"

      - name: Configure CMake
        run: |
          cmake -S . -B build \
            -DCMAKE_BUILD_TYPE=Release \
            -G Ninja
            -DCMAKE_OSX_SYSROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
            -DCMAKE_CXX_FLAGS="-isystem /opt/local/libexec/llvm-18/include/c++/v1"
            -DCMAKE_EXE_LINKER_FLAGS="
                -L/opt/local/libexec/llvm-18/lib/libc++ -Wl,
                -rpath,
                /opt/local/libexec/llvm-18/lib/libc++ -Wl,
                -rpath,
                /opt/local/lib -L/opt/local/lib -lunwind
            "
            -DCMAKE_SHARED_LINKER_FLAGS="
                -L/opt/local/libexec/llvm-18/lib/libc++ -Wl,
                -rpath,/opt/local/libexec/llvm-18/lib/libc++ -Wl,
                -rpath,/opt/local/lib -L/opt/local/lib -lunwind

      - name: Build
        run: |
          cmake --build build -j2
